<?php

require_once dirname(__FILE__) . '/../../../application/controller/AssortmentController.php';

/**
 * Test class for AssortmentController.
 * Generated by PHPUnit on 2012-04-12 at 11:43:49.
 */
class AssortmentControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AssortmentController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AssortmentController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AssortmentController::Store
     * @todo Implement testStore().
     */
    public function testStore() {
        $request = Application::getInstance() -> request;
        
        $request -> setParam('storeId', '6');
        
        $c = new AssortmentController;
        $result = $c -> Store();
    }

    /**
     * @covers AssortmentController::Save
     * @todo Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
