<?php

require_once dirname(__FILE__) . '/../../../application/controller/PersonController.php';

/**
 * Test class for PersonController.
 * Generated by PHPUnit on 2012-04-11 at 20:01:51.
 */
class PersonControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PersonController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PersonController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PersonController::Index
     * @todo Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PersonController::Add
     * @todo Implement testAdd().
     */
    public function testAdd() {
        $request = Application::getInstance() -> request;
        
        $request -> setParams(array(
            'name' => 'Louise the Zero',
            'type' => 'adult'
        ));
        
        $res = $this -> object -> add();
        $this -> assertTrue(isset($res['id']));

        
        
        $request -> setParams(array(
            'name' => 'Louise the Zero',
            'type' => 'OLOLOLO LOLO LOLO'
        ));
        
        $res = $this -> object -> add();
        $this -> assertTrue(isset($res['error']));
        
        $request -> setParams(array(
            'name' => '',
            'type' => ''
        ));
        
        $res = $this -> object -> add();
        $this -> assertTrue(isset($res['error']));
        
        $request -> setParams(array(
            'name' => 'Tristana',
            'type' => 'veteran'
        ));
        
        $res = $this -> object -> add();
        $this -> assertTrue(isset($res['id']));
    }

    /**
     * @covers PersonController::Remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
        $request = Application::getInstance() -> request;
        
        $request -> setParams(array(
            'name' => 'Louise the Zero',
            'type' => 'adult'
        ));
        
        $res = $this -> object -> Add();
        $this -> assertTrue(isset($res['id']));
        
        $id = $res['id'];
        
        $request -> setParams(array(
            'id' => $id
        ));
        
        $res = $this -> object -> Remove();
        $this -> assertFalse(isset($res['error']));
    }

}

?>
