<?php

require_once dirname(__FILE__) . '/../../../application/controller/QueueController.php';

/**
 * Test class for QueueController.
 * Generated by PHPUnit on 2012-04-12 at 22:01:28.
 */
class QueueControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var QueueController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new QueueController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers QueueController::Index
     * @todo Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QueueController::Add
     * @todo Implement testAdd().
     */
    public function testAdd() {
        $person = Person::factory('adult');
        $person -> name = 'Poehavshiy';
        $person -> add();
        
        $store = Store::factory('Grocery');
        $store -> name = 'Prison';
        $store -> add();
        
        $product = new Product;
        $product -> name = 'Sladkiy hleb';
        $product -> add();
        
        $request = Application::getInstance() -> request;
        
        $request -> setParams(array(
            'storeId' => $store -> id,
            'personId' => $person -> id,
            'product_'.$product -> id => 'on'
        ));

        
        $personId = $request -> p('personId');
        $storeId  = $request -> p('storeId');

        $store  = Store::get($storeId);
        $person = Person::get($personId); 

        $store  -> queue  -> add($person);
        $person -> basket -> drop();
        

        $name = 'product_'.$product -> id;
        $value = $product;
        
            if (preg_match_all('/^product_(\d+)$/', $name, $matches))
            {
                $person -> basket -> add(Product::get($matches[1][0]));
            }
    }

    /**
     * @covers QueueController::Ls
     * @todo Implement testLs().
     */
    public function testLs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QueueController::Remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
