<?php

require_once dirname(__FILE__) . '/../../../application/model/Assortment.php';

/**
 * Test class for Assortment.
 * Generated by PHPUnit on 2012-04-12 at 04:43:05.
 */
class AssortmentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Assortment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Assortment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Assortment::add
     * @todo Implement testAdd().
     */
    public function testAdd() {
        $db = Application::getInstance() -> mysqli;

        $db -> query('DELETE FROM Product');
        $db -> query('DELETE FROM Store');
        $db -> query('DELETE FROM Assortment');

        for ($i = 1; $i < 3; $i++)
        {
            $store = Store::factory('grocery');
            $store -> name = 'store_'.$i;
            $store -> add();
            $stores[] = $store;
        }
        
        for ($i = 1; $i < 10; $i++)
        {
            $product = new Product;
            $product -> name = 'product_'.$i;
            $product -> add();
            $products[] = $product;            
            
            $map[$product -> id] = rand(0,2);
        }
        
        $a = $stores[1] -> assortment;
        
        $a -> map($map);
    }

    /**
     * @covers Assortment::remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
    }

    /**
     * @covers Assortment::ls
     * @todo Implement testLs().
     */
    public function testLs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
