<?php

require_once dirname(__FILE__) . '/../../../application/model/Basket.php';

/**
 * Test class for Basket.
 * Generated by PHPUnit on 2012-04-11 at 18:11:18.
 */
class BasketTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Basket
     */
    protected $person;
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Basket;
        $this->person = new PersonAdult();
        $this->person -> name = 'Marisa Kirisame';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Basket::add
     * @todo Implement testAdd().
     */
    public function testAdd() {
        for ($i = 1; $i <= 10; $i++)
        {
            $product = new Product();
            $product -> id   = $i;
            $product -> name = 'My product '.$i;

            $this -> object -> add($product);
        }
        
        $this -> assertEquals($this -> object -> count(), 10);
    }

    /**
     * @covers Basket::remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
        $this -> testAdd();
        
        $product = new Product();
        $product -> id = 2;
        $this -> object -> remove($product);
        $this -> object -> remove(4);
        
        $this -> assertEquals($this -> object -> count(), 8);
    }

    /**
     * @covers Basket::sync
     */
    public function testLLSync() {
        $this -> object -> sync();
    }
    
    
    /**
     * @covers Basket::load
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}

?>
