<?php

require_once dirname(__FILE__) . '/../../../application/model/AdultPerson.php';

/**
 * Test class for AdultPerson.
 * Generated by PHPUnit on 2012-04-11 at 19:04:28.
 */
class AdultPersonTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AdultPerson
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PersonAdult;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Person::add
     * @todo Implement testAdd().
     */
    public function testAdd() {
        $person = new PersonAdult();
        $person -> name = 'Nyan Desu';
        $person -> type = 'adult';
        $person -> add();
        $person -> remove();

        try
        {
            $person -> name = '';
            $person -> add();
            $person -> remove();
            $this -> fail();
        } catch(Exception $e){
        }
        
        $person -> name = '\'" OLOLO LOLOLLOL PLOLO SQL INJ';
        $person -> type = 'adult';
        $person -> add();
    }
    
    /**
     * @covers Person::factory, Person::factoryGet
     */
    public function testFactory()
    {
        $person = new PersonAdult;
        $person -> name = 'Adult Lol';
        $person -> type = 'Adult';
        $person = Person::factory($person);
        
        $this -> assertTrue(get_class($person) == 'PersonAdult');
    }

    /**
     * @covers Person::remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
        $this -> object -> add();
    }

    /**
     * @covers Person::saveBasket
     * @todo Implement testSaveBasket().
     */
    public function testSaveBasket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Person::ls
     * @todo Implement testLs().
     */
    public function testLs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}

?>
