<?php

require_once dirname(__FILE__) . '/../../../application/model/Person.php';

/**
 * Test class for Person.
 * Generated by PHPUnit on 2012-04-11 at 18:25:24.
 */
class PersonTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Person
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Person::add
     * @todo Implement testAdd().
     */
    public function testAdd() {
    }
    
    /**
     * @covers Person::factory, Person::factoryGet
     */
    public function testFactory()
    {
    }

    /**
     * @covers Person::remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
    }

    /**
     * @covers Person::saveBasket
     * @todo Implement testSaveBasket().
     */
    public function testSaveBasket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Person::ls
     * @todo Implement testLs().
     */
    public function testLs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
