<?php

require_once dirname(__FILE__) . '/../../../application/model/Product.php';

/**
 * Test class for Product.
 * Generated by PHPUnit on 2012-04-11 at 17:00:59.
 */
class ProductTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Product
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Product;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Product::add
     * @todo Implement testAdd().
     */
    public function testAdd() {

    }

    /**
     * @covers Product::remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
        
    }

}

?>
