<?php

require_once dirname(__FILE__) . '/../../engine/TestBootstrap.php';

/**
 * Test class for TestBootstrap.
 * Generated by PHPUnit on 2012-04-11 at 18:11:15.
 */
class TestBootstrapTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TestBootstrap
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TestBootstrap;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TestBootstrap::run
     * @todo Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
