<?php

require_once dirname(__FILE__) . '/../../../engine/core/ActiveRecord.php';

/**
 * Test class for ActiveRecord.
 * Generated by PHPUnit on 2012-04-11 at 18:11:17.
 */
class ActiveRecordTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ActiveRecord
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ActiveRecord;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ActiveRecord::__get
     * @todo Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ActiveRecord::__set
     * @todo Implement test__set().
     */
    public function test__set() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ActiveRecord::setTable
     * @todo Implement testSetTable().
     */
    public function testSetTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ActiveRecord::getTable
     * @todo Implement testGetTable().
     */
    public function testGetTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ActiveRecord::isValidId
     * @todo Implement testIsValidId().
     */
    public function testIsValidId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ActiveRecord::_get
     * @todo Implement test_get().
     */
    public function test_get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
