<?php

require_once dirname(__FILE__) . '/../../../engine/core/Dispatcher.php';

/**
 * Test class for Dispatcher.
 * Generated by PHPUnit on 2012-04-11 at 18:11:15.
 */
class DispatcherTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Dispatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Dispatcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Dispatcher::getSearchDir
     * @todo Implement testGetSearchDir().
     */
    public function testGetSearchDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::setDefaultController
     * @todo Implement testSetDefaultController().
     */
    public function testSetDefaultController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::getDefaultController
     * @todo Implement testGetDefaultController().
     */
    public function testGetDefaultController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::setDefaultAction
     * @todo Implement testSetDefaultAction().
     */
    public function testSetDefaultAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::getDefaultAction
     * @todo Implement testGetDefaultAction().
     */
    public function testGetDefaultAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::setSearchDir
     * @todo Implement testSetSearchDir().
     */
    public function testSetSearchDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::create
     * @todo Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::getController
     * @todo Implement testGetController().
     */
    public function testGetController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dispatcher::run
     * @todo Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
