<?php

require_once dirname(__FILE__) . '/../../../engine/core/Request.php';

/**
 * Test class for Request.
 * Generated by PHPUnit on 2012-04-11 at 18:11:16.
 */
class RequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Request::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::getControllerName
     * @todo Implement testGetControllerName().
     */
    public function testGetControllerName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::getActionName
     * @todo Implement testGetActionName().
     */
    public function testGetActionName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::getControllerActionRequest
     * @todo Implement testGetControllerActionRequest().
     */
    public function testGetControllerActionRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::getParam
     * @todo Implement testGetParam().
     */
    public function testGetParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::setParam
     * @todo Implement testSetParam().
     */
    public function testSetParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::setParams
     * @todo Implement testSetParams().
     */
    public function testSetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::g
     * @todo Implement testG().
     */
    public function testG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::p
     * @todo Implement testP().
     */
    public function testP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::cookie
     * @todo Implement testCookie().
     */
    public function testCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Request::session
     * @todo Implement testSession().
     */
    public function testSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
