<?php

require_once dirname(__FILE__) . '/../../../engine/core/Response.php';

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-04-11 at 18:11:16.
 */
class ResponseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Response::title
     * @todo Implement testTitle().
     */
    public function testTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Response::templateFile
     * @todo Implement testTemplateFile().
     */
    public function testTemplateFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Response::pageFile
     * @todo Implement testPageFile().
     */
    public function testPageFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Response::asHTML
     * @todo Implement testAsHTML().
     */
    public function testAsHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Response::asJSON
     * @todo Implement testAsJSON().
     */
    public function testAsJSON() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Response::send
     * @todo Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
