<?php

require_once dirname(__FILE__) . '/../../../engine/core/View.php';

/**
 * Test class for View.
 * Generated by PHPUnit on 2012-04-11 at 18:11:17.
 */
class ViewTest extends PHPUnit_Framework_TestCase {

    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new View;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers View::setParam
     * @todo Implement testSetParam().
     */
    public function testSetParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::setParams
     * @todo Implement testSetParams().
     */
    public function testSetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::issetParam
     * @todo Implement testIssetParam().
     */
    public function testIssetParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::getParam
     * @todo Implement testGetParam().
     */
    public function testGetParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::getParams
     * @todo Implement testGetParams().
     */
    public function testGetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::setResponse
     * @todo Implement testSetResponse().
     */
    public function testSetResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::getResponse
     * @todo Implement testGetResponse().
     */
    public function testGetResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
